#
#        _ _   _           _                  _   _                 
#       (_) | | |         | |                | | (_)                
#   __ _ _| |_| |__  _   _| |__     __ _  ___| |_ _  ___  _ __  ___ 
#  / _` | | __| '_ \| | | | '_ \   / _` |/ __| __| |/ _ \| '_ \/ __|
# | (_| | | |_| | | | |_| | |_) | | (_| | (__| |_| | (_) | | | \__ \
#  \__, |_|\__|_| |_|\__,_|_.__/   \__,_|\___|\__|_|\___/|_| |_|___/
#   __/ |                                                           
#  |___/                        - http://www.network-science.de/ascii/                                                       
#

                                     
name: download fresh emojis

on:
  workflow_dispatch:
  # schedule:
  #   # Runs "at minute 55 past every hour" (see https://crontab.guru)
  #   - cron: '00 23 * * 6'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: setup py
      uses: actions/setup-python@v2
      with:
<<<<<<< HEAD
    - name: run my python
      run: python ez_emoji/download.py

#    - uses: actions/checkout@v2
#    - uses: actions/setup-python@v2
    - uses: jannekem/run-python-script-action@v1
      with:
        script: |
          import os
          print("Directory contents:")
          for f in os.listdir():
              print(f)
    - name: Print errors
      if: steps.script.outputs.error == 'true'
      run: |
        printenv "SCRIPT_STDOUT"
        printenv "SCRIPT_STDERR"
      env:
        SCRIPT_STDOUT: ${{ steps.script.outputs.stdout }}
        SCRIPT_STDERR: ${{ steps.script.outputs.stderr }} 


=======
        python-version: '3.9'
    - run: python ez_emoji/download.py
>>>>>>> e8985a7d7ee3bc97ca743e0d36b3f5ebe912200d
    - name: Add, Commit, Push
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git add -A
        git commit -m "automated emoji download"
        git push
